export enum RequestType {
  TEMPLATE_ID = 57,
  HIERARCHY_ID = 10,
  SUBGROUP_ID = 9,
  COUNTRIES_ALL = 16,
  PORTFOLIO_LIST = 62,
  STATES_BY_COUNTRYNAME = 17,
  CONTACT_GROUP_LIST = 37,
  CONTACT_COMPANY_LIST = 93,
  BUILDINGS_LIST = 130,
  PREMISE_TYPE_ID = 23,
  GET_AVAILABLE_SUB_PROJECTS = 86,
}

export enum ObjectTypeTypeID {
  CONTACT_OTTID = 500,
}
