export enum ETLDocumentImportStatus {
  NOTSTARTED = 0,
  SFTPFILEUPLOADING = 1,
  FILESUPLOADED = 2,
  FILESEXTRACTED = 3,
  FILESVALIDATED = 4,
  TemplateFileUploaded = 5,
  TEMPLATEVALIDATED = 6,
  TEMPLATEREADYTOPROCESS = 7,
  PROCESSING = 8,
  PROCESSCOMPLETED = 9,
}

export enum ETLDocImportLongProcess {
  UPLOADEXTRACTFILES = 0,
  VALIDATEFILES = 1,
  VALIDTEMPLATE = 2,
  MAPTOOBJECTS = 3,
}

export enum ETLDocumentImportStep {
  FILEUPLOADEXTRACT = 0,
  FILEVALIDATION = 1,
  TEMPLATEVALIDATION = 2,
  EXECUTE = 3,
}
