# Used for STAGE/PROD
# This is a copy of the Dockerfile that uses nginx-ca-prod.conf

# Stage 1: Compile and Build angular codebase
FROM public.ecr.aws/docker/library/node:16.19-alpine as build
ARG COSTAR_ENVIRONMENT=dev 
ARG DEVEXTREME_KEY
WORKDIR /app
COPY package*.json ./
COPY decorate-angular-cli.js ./
RUN npm set strict-ssl false
RUN npm install --force
COPY ./ /app/

RUN echo "building environment=$COSTAR_ENVIRONMENT" && \
        mkdir -p ./apps/mango-crem-features/central-auth/src/license && \
        echo "export const licenseKey = '$DEVEXTREME_KEY'" > ./apps/mango-crem-features/central-auth/src/license/devextreme-license.js
RUN npm run build:$COSTAR_ENVIRONMENT:microcomponent-central-auth

# Stage 2: Serve app with nginx server
FROM public.ecr.aws/nginx/nginx:alpine-slim as final
COPY ./config/nginx-ca-prod.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
RUN apk update && apk add --upgrade openssl
COPY --from=build /app/dist/apps/mango-crem-features/central-auth/ /usr/share/nginx/html
EXPOSE 8000
ENTRYPOINT ["nginx", "-g", "daemon off;"]

RUN touch /var/run/nginx.pid && \
        chown -R nginx:nginx /var/run/nginx.pid && \
        chown -R nginx:nginx /var/cache/nginx

USER nginx
